name: betterinsta
description: "BetterInsta"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  video_player: ^2.9.2
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: "^0.14.1"
  flutter_native_splash: ^2.4.2

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/ipv.png"
  min_sdk_android: 21

flutter_native_splash:
  color: "#000000"
  image: assets/images/ipv-trans.png
  android: true
  ios: true
  web: false

flutter:
  uses-material-design: true
  assets:
    - assets/images/ipv.png
